# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='category',
            field=models.CharField(blank=True, choices=[('newspaper', 'Newspaper'), ('celebrity', 'Celebrity'), ('politician', 'Politician'), ('user', 'User')], max_length=100, null=True),
        ),
    ]
