# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
        ('accounts', '0002_node_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth'),
        ),
    ]
