# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_node_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
