# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180207_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='category',
        ),
    ]
