# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_search_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 14, 8, 4, 551301, tzinfo=utc)),
        ),
    ]
