# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20180205_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='language',
            field=models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], default='tr', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='search',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 7, 13, 30, 272101, tzinfo=utc)),
        ),
    ]
