# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keychain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='stream',
            field=models.BooleanField(default=False),
        ),
    ]
