from polarization.secrets import TWITTER_KEY, TWITTER_SECRET

TWITTER_CONSUMER_KEY = TWITTER_KEY
TWITTER_CONSUMER_SECRET = TWITTER_SECRET


INFLUENCER_SECTOR_ALISVERIS = "alisveris"
INFLUENCER_SECTOR_BASIN_YAYIN = "basin-yayin"
INFLUENCER_SECTOR_DAYANIKLI_TUKETIM = "dayanikli-tuketim"
INFLUENCER_SECTOR_EGITIM = "egitim"
INFLUENCER_SECTOR_EGLENCE_YASAM = "eglence-yasam"
INFLUENCER_SECTOR_ENERJI = "enerji"
INFLUENCER_SECTOR_FENOMENLER = "fenomenler"
INFLUENCER_SECTOR_FINANS = "finans"
INFLUENCER_SECTOR_GIYIM = "giyim"
INFLUENCER_SECTOR_HIZLI_TUKETIM = "hizli-tuketim"
INFLUENCER_SECTOR_INTERNET = "internet"
INFLUENCER_SECTOR_KAMU = "kamu"
INFLUENCER_SECTOR_KURUMSAL = "kurumsal"
INFLUENCER_SECTOR_KULTUR_SANAT = "kultur-sanat"
INFLUENCER_SECTOR_ORGANIZASYON = "organizasyon"
INFLUENCER_SECTOR_OTOMOTIV = "otomotiv"
INFLUENCER_SECTOR_REKLAM_PAZARLAMA = "reklam-pazarlama"
INFLUENCER_SECTOR_SAGLIK = "saglik"
INFLUENCER_SECTOR_SEYAHAT = "seyahat"
INFLUENCER_SECTOR_SPOR = "spor"
INFLUENCER_SECTOR_TEKNOLOJI = "teknoloji"
INFLUENCER_SECTOR_URUN_HIZMET = "urun-hizmet"
INFLUENCER_SECTOR_YAPI_SEKTORU = "yapi-sektoru"
INFLUENCER_SECTOR_DIGER = "diger"
INFLUENCER_SECTOR_CHOICES = (
    (INFLUENCER_SECTOR_ALISVERIS, "Alışveriş"),
    (INFLUENCER_SECTOR_BASIN_YAYIN, "Basın"),
    (INFLUENCER_SECTOR_DAYANIKLI_TUKETIM, "Dayanıklı Tüketim"),
    (INFLUENCER_SECTOR_EGITIM, "Eğitim"),
    (INFLUENCER_SECTOR_EGLENCE_YASAM, "Eğlence"),
    (INFLUENCER_SECTOR_ENERJI, "Enerji"),
    (INFLUENCER_SECTOR_FENOMENLER, "Fenomen"),
    (INFLUENCER_SECTOR_FINANS, "Finans"),
    (INFLUENCER_SECTOR_GIYIM, "Giyim"),
    (INFLUENCER_SECTOR_HIZLI_TUKETIM, "Hızlı Tüketim"),
    (INFLUENCER_SECTOR_INTERNET, "İnternet"),
    (INFLUENCER_SECTOR_KAMU, "Kamu"),
    (INFLUENCER_SECTOR_KURUMSAL, "Kurumsal"),
    (INFLUENCER_SECTOR_KULTUR_SANAT, "Kültür Sanat"),
    (INFLUENCER_SECTOR_ORGANIZASYON, "Organizasyon"),
    (INFLUENCER_SECTOR_OTOMOTIV, "Otomotiv"),
    (INFLUENCER_SECTOR_REKLAM_PAZARLAMA, "Reklam"),
    (INFLUENCER_SECTOR_SAGLIK, "Sağlık"),
    (INFLUENCER_SECTOR_SEYAHAT, "Seyahat"),
    (INFLUENCER_SECTOR_SPOR, "Spor"),
    (INFLUENCER_SECTOR_TEKNOLOJI, "Teknoloji"),
    (INFLUENCER_SECTOR_YAPI_SEKTORU, "Yapı"),
    (INFLUENCER_SECTOR_DIGER, "Diğer")
)
